# Twitter error codes
TWITTER_PAGE_DOES_NOT_EXISTS_ERROR = 34
TWITTER_USER_NOT_FOUND_ERROR = 50
TWITTER_TWEET_NOT_FOUND_ERROR = 144
TWITTER_DELETE_OTHER_USER_TWEET = 183
TWITTER_ACCOUNT_SUSPENDED_ERROR = 64
